// ============================================================
// Jill Tokuda Dashboard — App.jsx
// Generated by BWPP Dashboard Builder
// Update DATA INPUTS section each reporting period
// ============================================================

import React, { useState } from "react";

// ── DATA INPUTS — update after each reporting cycle ──────────
const DATA = {
  period: "Current Period",

  email: {
    totalSends: 0,
    avgOpenRate: 0,
    avgClickRate: 0,
    listSize180DO: 0,
  },

  finances: {
    totalRaised: 191144.26,
    emailDigital: 16373.0,
    smsDigital: 0.0,
    digitalTarget: 0.10,
    byMonth: [
      { month: "2025-11", total: 25302.1, digital: 1886.0 },
      { month: "2025-12", total: 51323.1, digital: 60.0 },
      { month: "2026-01", total: 31344.1, digital: 3400.0 },
      { month: "2026-02", total: 45411.36, digital: 9281.0 },
      { month: "2026-03", total: 36895.1, digital: 1711.0 },
      { month: "2026-04", total: 868.5, digital: 35.0 }
    ],
  },

  texting: {
    campaigns: [
      { name: "251230_Tokuda_EOQ", date: "12/30/25", delivered: 403, clicked: 25, revenue: 0 },
      { name: "251231_Tokuda All Donors", date: "12/31/25", delivered: 1671, clicked: 76, revenue: 0 },
      { name: "JT_Birthday!", date: "3/10/26", delivered: 106, clicked: 6, revenue: 0 }
    ],
    costPerMsg: 0.07,
  },

  googleAds: {
    period: "N/A",
    campaigns: [
      // Add Google Ads campaigns here
    ],
  },
};

// ── AUTO-COMPUTED ─────────────────────────────────────────────
const totalDelivered = DATA.texting.campaigns.reduce((s,c) => s+c.delivered, 0);
const totalSpend = totalDelivered * DATA.texting.costPerMsg;
const totalRevenue = DATA.texting.campaigns.reduce((s,c) => s+c.revenue, 0);
const textingROAS = totalSpend > 0 ? totalRevenue / totalSpend : 0;
const totalDigital = DATA.finances.emailDigital + DATA.finances.smsDigital;
const digitalPct = DATA.finances.totalRaised > 0 ? totalDigital / DATA.finances.totalRaised : 0;

const emailRating = (rate) => {
  if (rate >= 0.25) return { label: "Excellent", color: "#22c55e" };
  if (rate >= 0.20) return { label: "Good", color: "#84cc16" };
  if (rate >= 0.15) return { label: "Average", color: "#f59e0b" };
  if (rate >= 0.10) return { label: "Below Avg", color: "#f97316" };
  return { label: "Poor", color: "#ef4444" };
};

function KPICard({ title, value, sub, color }) {
  return (
    <div style={{ border:"1px solid #e5e7eb", borderRadius:6, padding:16, background:"#fff", boxShadow:"0 1px 3px rgba(0,0,0,0.08)" }}>
      <div style={{ fontSize:13, color:"#6b7280", marginBottom:4 }}>{title}</div>
      <div style={{ fontSize:28, fontWeight:"bold", color:color||"#1F4E79" }}>{value}</div>
      {sub && <div style={{ fontSize:12, color:"#9ca3af", marginTop:4 }}>{sub}</div>}
    </div>
  );
}

export default function App() {
  const [tab, setTab] = useState("overview");
  const rating = emailRating(DATA.email.avgOpenRate);
  const TABS = ["overview","email","finances","texting","ads"];

  return (
    <div style={{ fontFamily:"Arial,sans-serif", maxWidth:1100, margin:"0 auto", padding:20 }}>
      <h1 style={{ background:"#1F4E79", color:"#fff", padding:"12px 20px", borderRadius:6, marginBottom:16 }}>
        Jill Tokuda — Digital Dashboard ({DATA.period})
      </h1>

      <div style={{ display:"flex", gap:8, marginBottom:20 }}>
        {TABS.map(t => (
          <button key={t} onClick={() => setTab(t)} style={{
            padding:"8px 16px", borderRadius:4, border:"none", cursor:"pointer",
            background: tab===t ? "#1F4E79" : "#e5e7eb",
            color: tab===t ? "#fff" : "#374151",
            fontWeight: tab===t ? "bold" : "normal",
            textTransform:"capitalize"
          }}>{t}</button>
        ))}
      </div>

      {tab==="overview" && (
        <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:16 }}>
          <KPICard title="Total Sends (Email)" value={DATA.email.totalSends} />
          <KPICard title="Avg Open Rate" value={(DATA.email.avgOpenRate*100).toFixed(1)+"%"} sub={rating.label} color={rating.color} />
          <KPICard title="Total Raised" value={"$"+DATA.finances.totalRaised.toLocaleString()} />
          <KPICard title="Digital Raised" value={"$"+totalDigital.toLocaleString()} sub={(digitalPct*100).toFixed(1)+"% of total (10% target)"} color={digitalPct>=0.10?"#22c55e":"#ef4444"} />
          <KPICard title="Texts Delivered" value={totalDelivered.toLocaleString()} sub={DATA.texting.campaigns.length+" campaigns"} />
          <KPICard title="Texting Spend" value={"$"+totalSpend.toFixed(2)} sub="@ $0.07/msg" />
        </div>
      )}

      {tab==="email" && (
        <div>
          <h2>Email Performance</h2>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:12, marginBottom:16 }}>
            <KPICard title="Total Sends" value={DATA.email.totalSends} />
            <KPICard title="Avg Open Rate" value={(DATA.email.avgOpenRate*100).toFixed(1)+"%"} color={rating.color} sub={rating.label} />
            <KPICard title="Avg Click Rate" value={(DATA.email.avgClickRate*100).toFixed(1)+"%"} />
          </div>
        </div>
      )}

      {tab==="finances" && (
        <div>
          <h2>ActBlue Finances</h2>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:12, marginBottom:16 }}>
            <KPICard title="Total Raised" value={"$"+DATA.finances.totalRaised.toLocaleString()} />
            <KPICard title="Digital Raised" value={"$"+totalDigital.toLocaleString()} sub="Email + SMS" />
            <KPICard title="Digital %" value={(digitalPct*100).toFixed(1)+"%"} sub={digitalPct>=0.10?"✓ Met 10% Target":"✗ Below 10% Target"} color={digitalPct>=0.10?"#22c55e":"#ef4444"} />
          </div>
          <table style={{ width:"100%", borderCollapse:"collapse" }}>
            <thead><tr style={{ background:"#1F4E79", color:"#fff" }}>
              {["Month","Total Raised","Digital Raised","Digital %","Status"].map(h => (
                <th key={h} style={{ padding:"8px", textAlign:h==="Month"?"left":"right" }}>{h}</th>
              ))}
            </tr></thead>
            <tbody>
              {DATA.finances.byMonth.map((m,i) => {
                const pct = m.total>0 ? m.digital/m.total : 0;
                return (
                  <tr key={m.month} style={{ background:i%2===0?"#D6E4F0":"#fff" }}>
                    <td style={{ padding:"6px 8px" }}>{m.month}</td>
                    <td style={{ padding:"6px 8px", textAlign:"right" }}>${"$"+m.total.toLocaleString()}</td>
                    <td style={{ padding:"6px 8px", textAlign:"right" }}>${"$"+m.digital.toLocaleString()}</td>
                    <td style={{ padding:"6px 8px", textAlign:"right" }}>{(pct*100).toFixed(1)+"%"}</td>
                    <td style={{ padding:"6px 8px", textAlign:"right", color:pct>=0.10?"#22c55e":"#ef4444" }}>{pct>=0.10?"✓ Met":"✗ Below"}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {tab==="texting" && (
        <div>
          <h2>Texting ROI</h2>
          <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:12, marginBottom:16 }}>
            <KPICard title="Total Delivered" value={totalDelivered.toLocaleString()} />
            <KPICard title="Total Spend" value={"$"+totalSpend.toFixed(2)} sub="@ $0.07/msg" />
            <KPICard title="ROAS" value={totalRevenue>0?textingROAS.toFixed(2)+"x":"—"} sub="Enter revenue to calculate" />
          </div>
        </div>
      )}

      {tab==="ads" && (
        <div>
          <h2>Google Ads — {DATA.googleAds.period}</h2>
        </div>
      )}
    </div>
  );
}
